#!/bin/sh

#	(c) 2010 Frederic Pasteleurs <frederic@askarel.be>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

ACCOUNT="BE69979429775578"
BANKFILE="./bank/$ACCOUNT-year-$1-full.csv"
EMPTYRESULTFILE="$0.unpaid"
test -z "$1" && echo "Please tell me what year on the command line" && exit 1

test -e $EMPTYRESULTFILE && rm $EMPTYRESULTFILE && touch $EMPTYRESULTFILE
test -e $BANKFILE || echo "$BANKFILE not found"
test -e $BANKFILE || exit 1

./hsb-members list-current|tail -n +2 | while read LINE; do

echo "-- $(echo $LINE| cut -d ',' -f 5) ($(echo $LINE| cut -d ',' -f 3-4), entered on $(echo $LINE| cut -d ',' -f 1))  ------------------------------------------------"
cat $BANKFILE| grep "$(echo $LINE | cut -d ',' -f 2)"
test "$(cat $BANKFILE| grep "$(echo $LINE | cut -d ',' -f 2)" | wc -l )" -eq "0" && echo "$LINE"|cut -d ',' -f 7 >> $EMPTYRESULTFILE

done

