#!/bin/sh

#	(c) 2010 Frederic Pasteleurs <frederic@askarel.be>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

ME=$(basename $0)
CONF="./member-mailer.conf"
UNPAID="$ME.unpaid"

############### <FUNCTIONS> ###############
# Function to call when we bail out
die ()
{
    echo "$ME: $1. Exit"
    if [ "_$2" = "_" ]; then
	exit 1
	else
	exit $2
    fi
}

# Load and check config file
test -f $CONF || die "$CONF do not exist"
. $CONF
test -n "$MEMBER_FILE" || die "$CONF: MEMBER_FILE variable is empty"
test -n "$ACCOUNTNUMBER" || die "$CONF: ACCOUNTNUMBER variable is empty"
test -n "$MAILFROM" || die "$CONF: MAILFROM variable (sender e-mail address) is empty"
test -n "$MEMBERSHIPFEE" || die "$CONF: MEMBERSHIPFEE variable is empty"
#test -n "$FREETEXT" || die "$CONF: FREETEXT variable (mail body) is empty"
test -f "$MEMBER_FILE" || die "File $MEMBER_FILE do not exist"

test -f $UNPAID || die "Cool !! Members pay their bills" 0 
exit 0

for i in $(cat $UNPAID); do
    REMIND="$(./hsb-members list-current|grep $i)"
    FIRSTNAME=$(echo $REMIND|cut -d ',' -f 3)
    COMMUNICATION=$(echo $REMIND|cut -d ',' -f 2)
    DEST_EMAIL=$(echo $REMIND|cut -d ',' -f 7)
    echo "Reminding $FIRSTNAME ($DEST_EMAIL)..."
############################################################################## <- EOL
	echo "
Hello $FIRSTNAME,

Today is general assembly day and we noticed that you did not contribute financially
to the hackerspace project while still being registered in our database
as an active member.

In case you want to keep your membership active, here are the banking informations
for your contribution:
Bank account number: $ACCOUNTNUMBER (unchanged)
Membership fee: $MEMBERSHIPFEE euros per month
Communication field: $COMMUNICATION

If you want to terminate your membership, just say so in your reply and we will
not bother you anymore.

This is the last warning. If we don't hear from you, your membership 
will be automatically cancelled.

-- 
Hackerspace Brussels

This mail is sent automagically from another broken half-assed bash script. :-)
"| mail -s "Hackerspace Brussels - membership reminder 1" $DEST_EMAIL


done

exit 0
